### ISSUE TITLE
[Suggestion] Drop table?

### ISSUE THREAD

**Issue by Numpty-Clodpole** [BillyGalbreath/Kraken#1]
I'd like to know if you would be willing to add a configurable custom drop table, one that people can enable/disable if they'd rather not have one. The owner of the server that I'm the SysAdmin of (@aegisjester) wants to use this, but only if we are able to add custom drops to it.

**Comment by BillyGalbreath** [comment]
Loot table support added.

Provided a datapack sample in the plugin folder. To use it set `loot-table: "kraken:kraken"` in config.yml after installing the datapack to your server ;)
